version: '3.8'
services:
  mongo_primary:
    image: mongo:6.0
    container_name: mongo_primary
    ports:
      - 27017:27017
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - mongo_net

  mongo_backup:
    image: mongo:6.0
    container_name: mongo_backup
    ports:
      - 27018:27017
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge