version: '3.8'
services:
  mongo_primary:
    image: mongo:6
    container_name: mongo_primary
    restart: always
    ports:
      - "27017:27017"
    command: --replSet rs0
    volumes:
      - /Users/andyxiao/mongo_primary_data:/data/db
    networks:
      - mongo_net

networks:
  mongo_net:
    external: true